<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class SetLocale
{
    /**
     * Supported locales for this application.
     * Generated by Lyngo based on your project's configured languages.
     */
    protected array $supported = ['pt_BR', 'en'];

    protected string $default = 'en';

    public function handle(Request $request, Closure $next): Response
    {
        // Strategy 1: Session/cookie (default)
        // Reads locale from session or cookie, set via a language switcher route.
        $locale = session('locale', $request->cookie('locale'));

        // Strategy 2: URL segment (uncomment to use)
        // Reads the first URL segment, e.g. /fr/dashboard
        // $locale = $request->segment(1);

        // Strategy 3: Accept-Language header (uncomment to use)
        // Reads the browser's preferred language.
        // $locale = $request->getPreferredLanguage($this->supported);

        if ($locale && in_array($locale, $this->supported)) {
            app()->setLocale($locale);
        } else {
            app()->setLocale($this->default);
        }

        return $next($request);
    }
}